### ISSUE TITLE
implement travis ci in master branch

### ISSUE THREAD

**Issue by CloudBreadPaPa** [CloudBreadProject/CloudBread-Admin-Web#33]
implement travis ci in master branch
https://docs.travis-ci.com/user/languages/javascript-with-nodejs/#Node.js-v4-(or-io.js-v3)-compiler-requirements

```
language: node_js
node_js:
  - "4"
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
```
